import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import FontAwesomeConfig from "./fontawesome";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHome } from '@fortawesome/free-solid-svg-icons';

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: '/images/fe-logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body className="bg-gray-100 text-gray-800">
        <Link href="/" className="fixed top-4 left-4 bg-orange-600 text-white px-3 py-2 rounded-full shadow-lg hover:bg-orange-700 transition-all z-50">
          <FontAwesomeIcon icon={faHome} />
        </Link>

        {children}
      </body>
    </html>
  );
}
